# Generated by Django 5.0.2 on 2024-03-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='updated',
        ),
    ]
