# Generated by Django 5.0.2 on 2024-03-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='oil',
            name='name',
        ),
        migrations.RemoveField(
            model_name='oil',
            name='slug',
        ),
        migrations.AlterField(
            model_name='oil',
            name='API',
            field=models.CharField(choices=[('SM', 'SM'), ('SN', 'SN'), ('SL', 'SL'), ('SF', 'SF')], default='SN', max_length=255),
        ),
    ]
