# Generated by Django 5.0.2 on 2024-03-19 15:24

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_battery_remove_oil_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='API',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Flow',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Fuel_consumption',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Guarantee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volume',
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('Flow', models.PositiveIntegerField()),
                ('desc', models.TextField()),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battery_brand', to='products.brandbattery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='battery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_battery', to='products.battery'),
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('API', models.CharField(choices=[('SM', 'SM'), ('SN', 'SN'), ('SL', 'SL'), ('SF', 'SF')], default='SN', max_length=255)),
                ('Fuel_consumption', models.CharField(choices=[('Gasoline', 'گازوئیل'), ('oil', 'بنزین'), ('CNG', 'گازسوز')], default='oil', max_length=255)),
                ('Guarantee', models.CharField(choices=[('0W-30', '0W-30'), ('5W-30', '5W-30'), ('10W-30', '10W-30'), ('10W-40', '10W-40'), ('15W-40', '15W-40')], default='10W-30', max_length=255)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oil_brand', to='products.brandoil')),
                ('volume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oil_volume', to='products.volumeoil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='oil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_oil', to='products.oil'),
        ),
    ]
