# Generated by Django 5.0.2 on 2024-03-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_api_remove_product_flow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oil',
        ),
    ]
