# Generated by Django 5.0.2 on 2024-03-21 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_category_one_consumables_category_one_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_two',
            name='battery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables_battery', to='products.battery'),
        ),
        migrations.AlterField(
            model_name='category_two',
            name='oil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables_oil', to='products.oil'),
        ),
    ]
