# Generated by Django 5.0.2 on 2024-03-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_category_two_battery_remove_category_two_oil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oil',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='oil',
            name='volume',
        ),
        migrations.DeleteModel(
            name='Battery',
        ),
        migrations.DeleteModel(
            name='BrandBattery',
        ),
        migrations.DeleteModel(
            name='BrandOil',
        ),
        migrations.DeleteModel(
            name='Oil',
        ),
        migrations.DeleteModel(
            name='VolumeOil',
        ),
    ]
