# Generated by Django 5.0.2 on 2024-03-26 18:37

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_oil_brand_remove_oil_volume_delete_battery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryAttrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('category2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs_cat', to='products.category_two')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
