# Generated by Django 5.0.2 on 2024-03-27 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_attribute_attributevalue_product_attrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_two',
            name='atrss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atrss_cat', to='products.attributevalue'),
        ),
    ]
