# Generated by Django 5.0.2 on 2024-03-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_battery_brandbattery_brandoil_volumeoil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%M/%d'),
        ),
    ]
