# Generated by Django 5.0.2 on 2024-03-31 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_battery_brandbattery_brandoil_volumeoil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='galleryProduct/%y/%M/%d')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='imageGallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galleryProduct', to='products.galleryproduct'),
        ),
    ]
