# Generated by Django 5.0.2 on 2024-04-03 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_product_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandOil',
            new_name='Brand',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='category_two',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='oil',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='oil',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='category_two',
            name='oil',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productBrand', to='products.brand'),
        ),
        migrations.DeleteModel(
            name='BrandBattery',
        ),
        migrations.DeleteModel(
            name='Battery',
        ),
        migrations.DeleteModel(
            name='VolumeOil',
        ),
        migrations.DeleteModel(
            name='Oil',
        ),
    ]
