# Generated by Django 5.0.2 on 2024-04-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_rename_brandoil_brand_remove_battery_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='englishName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
