# Generated by Django 5.0.2 on 2024-04-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_comment_is_replay_alter_comment_replay_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
