# Generated by Django 5.0.2 on 2024-04-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_comment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_replay',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='replay_to',
        ),
    ]
