# Generated by Django 5.0.2 on 2024-03-29 14:57

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/%Y/%M/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
